### ISSUE TITLE
Invalid declaration of inverse CNOTs in clifford_plus_t_direct_transform

### ISSUE THREAD

**Issue by JonhasSC** [isi-usc-edu/pyLIQTR#11]
I found this issue when when trying to perform a Clifford + T transformation over an inverse CNOT operation. I'm using `pyLIQTR==1.0.0` and `python 3.11.5`
Consider the following code block:
```python
qb = cirq.LineQubit.range(2)
circuit = cirq.Circuit([
    cirq.inverse(cirq.CNOT(qb[0], qb[1])),
])
cpt_circ = clifford_plus_t_direct_transform(circuit)
```
This will generate the following gates:
```
CNOT**-1.0(q(0), q(1)
```
which isn't a valid declaration mapping to some backend representation. If i were to print out this instruction's corresponding qasm:
```python
cirq.QasmOutput(cpt_circ, cpt_circ.all_qubits()).save('inverse_cnot.qasm')
```
cirq will generate the following:
```
// Gate: CNOT**-1.0
ry(pi*-0.5) q[1];
u3(pi*0.5,0,pi*1.25) q[0];
u3(pi*0.5,pi*1.0,pi*1.75) q[1];
sx q[0];
cx q[0],q[1];
rx(0) q[0];
ry(pi*0.5) q[1];
cx q[1],q[0];
sxdg q[1];
s q[1];
cx q[0],q[1];
u3(pi*0.5,pi*1.25,pi*1.0) q[0];
u3(pi*0.5,pi*0.75,0) q[1];
ry(pi*0.5) q[1];
```
which isn't a Clifford + T subcircuit. 

In the `clifford_plus_t_direct_transform` function living in the `pyLIQTR.gate_decomp.cirq_transforms` module, the inverse cnot gate gets evaluated in the second branch, i.e, 
```python
elif (
    len(op.qubits) != 1
    or is_gate_clifford_plus_T(op.without_classical_controls())
    or "Measurement" in str(op)
):
    operations.append(op)
```
where no transformation is done. This function claims that any gate that is added to the list of operations belong to the Clifford + T gateset. It would be helpful if there is some functionality to perform the CNOT**-1 transformation, such as H CNOT H, somewhere here to be able to generate the appropriate qasm.

**Comment by akurlej** [comment]
Hi Jonhas

```
import cirq

from   pyLIQTR.utils.printing                                 import openqasm
from pyLIQTR.gate_decomp.cirq_transforms import clifford_plus_t_direct_transform

qb = cirq.LineQubit.range(2)
circuit = cirq.Circuit([cirq.inverse(cirq.CNOT(qb[0],qb[1]))])
cpt_circ = clifford_plus_t_direct_transform(circuit)

for line in openqasm(cpt_circ):
    print(line)
```

will produce

```
// Generated from Cirq, Openfermion, and MIT LL

OPENQASM 2.0;
include "qelib1.inc";

// Qubits: [q(0), q(1)]
qreg q[2];


cx q[0],q[1];
```

If you are using the cirq.QasmOutput functionality, you may see 'weird' behavior, particularly when it comes to inverse-gates.  They dont seem very clever with how they catch gates that are self-inverse, and instead seem to go down a different execution pathway which results in those additional rotations and u3 gates. Because of our own frustrations with this, we ended up implementing our own qasm printing function (`pyLIQTR.utils.printing.openqasm`) and generally have guided folks to using that in our example notebooks (see the various pyLIQTR likes). 

I'm a little bit confused by H CNOT H comment though...the inverse of a CNOT gate is itself the CNOT. So what are you referring to?

**Comment by JonhasSC** [comment]
Thanks for the help, this clears up my confusion so I'll proceed to use pyLIQTR's openqasm functionality rather than cirq's. Regarding the CNOT comment, I assumed the inverse in this case was expressing CNOT(1 -> 2)**-1 = CNOT(1 <- 2) where the arrow is pointing at the target qubit.
