### ISSUE TITLE
Incorrect QASM for Measure Op

### ISSUE THREAD

**Issue by JonhasSC** [isi-usc-edu/pyLIQTR#14]
Generating qasm through the openqasm function for a corresponding circuit with just a measure operation results in invalid qasm.
```
pyLIQTR version: 1.2.0
python version: 3.12.0
OS: MacOS Sonoma 14.5
``` 
Consider the following circuit:
```
prec_8: ───M('measure_0')───
```

For a circuit with just a measure operation, I do the following:
```python
qasm_iter = openqasm(
        circuit=circuit,
        rotation_allowed=True
)
qasm_str = ' \n'.join([qasm for qasm in qasm_iter])
```
note that I specify rotations_allowed=True as I do not intend to decompose or perform a cpt transformation on just a circuit with a measure operation. Once I have the qasm str, I have the following:
```
// Generated from Cirq, Openfermion, and MIT LL

OPENQASM 2.0;
include "qelib1.inc";

// Qubits: [prec_18]
qreg q[1];

 
measure q[0] -> measure_0[q[0]]
```
which is not only missing a creg declaration, but the measure operation is an invalid expression. Assuming that `measure_0` was supposed to be a classical register, having the index to the classical register be an accessed value from a quantum register isn't valid qasm. 

I would expect either a correct opeqasm2.0 or openqasm3.0 expression and a creg declaration

**Comment by akurlej** [comment]
Hi Jonhas,

You've stumbled upon a known issue that we're aware about and have been waiting to hear if it causes an issue (congrats!).

Cirq seemingly doesnt fully support measurement gates as well as other cirq/qualtran operations/ancilla management, and this required us to implement a fallback/our own implementation (ie, this openqasm utility youre looking at). So you're witnessing our adhoc solution to remain within the spirit of openqasm while not having the ability to fully modify cirq/qualtran to support openqasm2.0/3.0. In addition to measurement, you will likely also find that classically controlled operations are a little 'wonky' (since cirq doesnt explicitly support translation to openqasm, we also had to bandage this). I think until cirq/qualtran supports openqasm3, we wont support it and until cirq fully supports openqasm2, we have our adhoc implementations/bandaids.

The intent of "measure q[0] -> measure_0[q[0]]" was to capture the measurement of an entire register/qbit and note which measurement bit holds the result of which qubit (hence the indexing). We didnt support the creg declaration because cirq also didnt natively support it, and to otherwise support it would require us looping through the entire output and determining how many unique measurement results there are (which we didnt think was useful).

We've made some changes to openqasm printing recently that should be more memory efficient and faster, and it might enable us to do this counting of measurements more easily (though we'd need to look at the overhead to speed this might introduce). This would then enable us to declare the various classical registers at the beginning and I think enable us to implement the measurement output more appropriately (though I'd have to think through some edge cases that might come up that could prevent this).

Additionally, are you directly importing openqasm2 or just parsing the output as string?

**Comment by JonhasSC** [comment]
Hi there,

Thank you for in depth response. I intend to just parse the qasm output as a string. Just to confirm, are you saying that for the expression "measure q[0] -> measure_0[q[0]]" is stating that the 0th classical bit will contain the result of the index, which is qubit 0? So, similarly, if we had "measure q[1] -> measure_0[q[1]]" this would say that the 0th classical bit will contain the result of the collapsed qubit, which is qubit 1 in this case?

is it reasonable to say that creg declarations is a possible feature in the future?

**Comment by rroodll** [comment]
addressed by supporting proper openqasm measurement spec
